POST http://localhost:9090/api/v1/posts
content-type: application/json

{
    "title": "Leveraging GORM in Go Lang",
    "body": "Simple CRUD REST API in Go Lang utilising GORM as ORM and Gin frameworks"
}