PUT http://localhost:9090/api/v1/posts/3
content-type: application/json

{
    "title": "Utilizing GORM in Go",
    "body": "CRUD REST API in Go Lang utilizing GORM as ORM and Gin lightweight, scalable frameworks"
}